source 'http://rubygems.org'

gem 'rails', '3.0.10'

gem 'pg'
gem 'fog'
gem 'thin'
gem "recaptcha", :require => "recaptcha/rails"

group :development, :test do
  gem 'sqlite3-ruby', :require => 'sqlite3'
end

# REFINERY CMS ================================================================
# Anything you put in here will be overridden when the app gets updated.

gem 'refinerycms',              '~> 1.0.9'

=begin #testing
group :development, :test do
  # To use refinerycms-testing, uncomment it (if it's commented out) and run 'bundle install'
  # Then, run 'rails generate refinerycms_testing' which will copy its support files.
  # Finally, run 'rake' to run the tests.
  gem 'refinerycms-testing',    '~> 1.0.9'
  gem 'capybara-webkit'

  if RbConfig::CONFIG['target_os'] =~ /darwin/i
    gem 'growl'
  end

  gem 'spork', '~> 0.9.0.rc', :platforms => :ruby
  gem 'guard-spork', :platforms => :ruby
  gem 'guard-rspec', :platforms => :ruby
  gem 'generator_spec'
end

=end #testing

# END REFINERY CMS ============================================================

# USER DEFINED

gem 'refinerycms-i18n',         '~> 1.0.0'

# END USER DEFINED

gem 'refinerycms-libraries', '1.0', :path => 'vendor/engines'

gem 'refinerycms-contacts', '1.0', :path => 'vendor/engines'
